name: Scroll Teleportation
author: Staartvin
website: http://dev.bukkit.org/server-mods/scroll-teleportation/
main: me.staartvin.scrollteleportation.ScrollTeleportation
version: 1.1
description: A cool RPG-like teleportation method with scrolls.
permissions:
    scrollteleportation.teleport:
        description: Allows a player to use scrolls
        default: op
    scrollteleportation.give:
        description: Allows a player to give scrolls
        default: op
    scrollteleportation.walkbypass:
        description: Players with this permission can walk while teleports are being casted
        default: op
    scrollteleportation.delaybypass:
        description: Players with this permission can bypass delays.
        default: op
    scrollteleportation.usesbypass:
        description: Players with this permission can bypass uses.
        default: op    
    scrollteleportation.potioneffectbypass:
        description: Players with this permission can bypass potioneffects.
        default: op
    scrollteleportation.set:
        description: Allows a player to set a variable
        default: op
    scrollteleportation.create:
        description: Allows a player to create scrolls
        default: op
    scrollteleportation.reload:
        description: Allows a player to reload config files
        default: op          
commands:
    scroll:
      description: Global command of Scroll Teleportation
      usage: /<command>
      aliases: [st, scrollteleportation, scrolls]